name: Build EXE
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build windows executable
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v1
      - name: install requirements
        run: >
          pip install -r requirements.txt
      - name: Debug
        run: >
          pip show customtkinter
          