name: Build EXE
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build windows executable
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v1
      - name: install requirements
        run: >
          pip install -r requirements.txt
      - name: install pyinstaller
        run: >
          pip install pyinstaller
      - name: Pack exe
        run: >
          pyinstaller --noconfirm --onedir --windowed --add-data "/home/runner/.local/lib/python3.8/site-packages/customtkinter:customtkinter" src/main.py --add-data "src/:src"
      - name: Debug
        run: >
          ls -la dist/
          