name: Build Binary
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build binary
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v1
      - name: install requirements
        run: >
          pip install -r requirements.txt
      - name: install pyinstaller
        run: >
          pip install pyinstaller
      - name: Pack binary
        run: >
          pyinstaller --noconfirm --onefile --name csgoatt --windowed src/main_qt.py --add-data "src/:src" --add-data "ui/:ui"
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: csgoatt
          path: dist/csgoatt